version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/ssl:ro
    networks:
      - mynetwork
    depends_on:
      - timebuddy_pocketbase

networks:
  mynetwork:
    driver: bridge

volumes:
  pb_data:
